### ISSUE TITLE
Fix Flake8 issues

### ISSUE THREAD

**Issue by abhinuvpitale** [abhinuvpitale/ppm-impy#1]
flake issues [here](https://travis-ci.com/abhinuvpitale/ppm-impy/builds/87837552)

**Comment by abhinuvpitale** [comment]
Feel free to PR here

**Comment by beeblebroccoli** [comment]
I've fixed the PEP8 issues as mentioned. I've also changed around the directory structure a bit and added pytest. This should help you avoid having to hack your path and give you an easy-to-use testing library.

Simply run py.test in the root of your project to execute the tests. As of right now the tests are just the pre-existing ones except wrapped in test functions.
The outputs are placed in the ppm/ directory.

I've also changed the project's python version from 2.7 to 3.6. It seems as though you were using Python3 print functions while still listing the project as 2.7. If this was in error, please let me know.
